### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by tonsquemike** [ml2grow/GAEPyPI#1]
I tried to login into webapp however I can´t do it
This is the content of my config.json file
`{
  "accounts": [
    {
      "username": "miguel",
      "password": "123"
    }
  ]
}
`

 Here is the output of `python setup.py sdist upload -r local`
> Writing Package-1.0/setup.cfg
Creating tar archive
removing 'Package-1.0' (and everything under it)
running upload
Submitting dist/Package-1.0.tar.gz to https://libraries-caja.appspot.com
Upload failed (401): Unauthorized
error: Upload failed (401): Unauthorized

**Comment by javdrher** [comment]
Hi @tonsquemike !

The error you are getting seems to indicate the authentication is set up correctly on your server but your upload fails to authenticate. Did you modify `~/.pypirc` and include the username/password? What happens if you go to your application by browser and login?

**Comment by tonsquemike** [comment]
Dear @javdrher thanks for your help, the problem was that I used the SHA1 string on `config.json` and also the SHA1 string as password in the `~/.pypirc` file.
