### ISSUE TITLE
List easier options for SHA1

### ISSUE THREAD

**Issue by gerardsimons** [ml2grow/GAEPyPI#8]
You can more easily make a SHA1 hash with CLI tools like openssl, perhaps list that in the README.md instead of having to rely on another Python package, although I guess the downside is that the password will end up in your bash history

`echo -n "yourpassword" | openssl sha1`

or

`echo -n "yourpassword" | shasum`

**Comment by javdrher** [comment]
Hi @gerardsimons , thank you for your interest in our package!

Checked those, they seem to give the same result. Feel free to make a PR editing the documents

**Comment by gerardsimons** [comment]
Will do!

**Comment by gerardsimons** [comment]
Tried to push a branch but getting a 403. Not sure if I can make a pull request then?

**Comment by javdrher** [comment]
Try again, fixed permissions 

(though forking, then opening a PR was working before)
